<?php
declare(strict_types=1);

namespace Helmich\Schema2Class\Generator\ReferencedType;

use Helmich\Schema2Class\Generator\GeneratorRequest;
use Helmich\Schema2Class\Generator\Enum\SchemaToEnum;
use Helmich\Schema2Class\Util\EnumUtils;

/**
 * Reference to a generated PHP Enum.
 *
 * Depending on the target PHP version and options it may either map to a native enum
 * generated by {@see SchemaToEnum} or to a set of primitive values.
 * 
 * Just like {@see ReferencedTypeClass}
 * it resolves type hints and annotations relative to the current namespace
 * so that the generated code can refer generated Enums correctly.
 */
readonly class ReferencedTypeEnum implements ReferencedTypeInterface
{
    /**
     * @param string $enumName Fully-qualified enum class name
     * @param array<array-key, string|int|array> $schema Schema definition of the enum
     */
    public function __construct(
        private string $enumName,
        private array $schema,
        private GeneratorRequest $request,
    ) {}

    private function canUseNativeEnum(): bool
    {
        return SchemaToEnum::canGenerateEnum($this->schema, $this->request);
    }

    private function relativeName(): string
    {
        $ns = $this->request->getTargetNamespace();
        if ($ns !== '' && str_starts_with($this->enumName, $ns . '\\')) {
            return substr($this->enumName, strlen($ns) + 1);
        }

        return '\\' . $this->enumName;
    }

    public function typeAnnotation(): string
    {
        if ($this->canUseNativeEnum()) {
            return $this->relativeName();
        }

        return EnumUtils::typeAnnotation($this->schema['enum']);
    }

    public function typeHint(): ?string
    {
        if ($this->canUseNativeEnum()) {
            return $this->relativeName();
        }

        return EnumUtils::typeHint($this->schema['enum'], $this->request->getTargetPHPVersion());
    }

    function serializedInputTypeHint(): ?string
    {
        return $this->typeHint();
    }

    public function serializedTypeHint(): ?string
    {
        return $this->typeHint();
    }

    public function serializedTypeHintStdClass(): ?string
    {
        return $this->serializedTypeHint();
    }

    public function typeAssertionExpr(string $expr): string
    {
        if ($this->canUseNativeEnum()) {
            return "{$expr} instanceof " . $this->relativeName();
        }

        return EnumUtils::assertionExpr($this->schema['enum'], $expr);
    }

    public function inputAssertionExpr(string $expr): string
    {
        if ($this->canUseNativeEnum()) {
            return $this->relativeName() . "::tryFrom({$expr}) !== null";
        }

        return EnumUtils::assertionExpr($this->schema['enum'], $expr);
    }

    public function inputMappingExpr(string $expr, bool $asserted = false): string
    {
        if ($this->canUseNativeEnum()) {
            return $this->relativeName() . "::from({$expr})";
        }

        return $expr;
    }

    public function outputMappingExpr(string $expr): string
    {
        if ($this->canUseNativeEnum()) {
            return "{$expr}->value";
        }

        return $expr;
    }

    public function outputMappingExprStdClass(string $expr): string
    {
        return $this->outputMappingExpr($expr);
    }

    public function usesNativeEnum(): bool
    {
        return $this->canUseNativeEnum();
    }

}