#!/usr/bin/env php
<?php
declare(strict_types = 1);

if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
} else if (file_exists(__DIR__ . '/../../../autoload.php')) {
    /** @noinspection PhpIncludeInspection */
    require_once __DIR__ . '/../../../autoload.php';
} else {
    die('Could not find an autoload.php. Did you set up all dependencies?');
}

$app = new \Symfony\Component\Console\Application("s2c");
$loader = new \Helmich\Schema2Class\Loader\SchemaLoader();
$inferrer = new \Helmich\Schema2Class\Generator\NamespaceInferrer();
$factory = new \Helmich\Schema2Class\Generator\SchemaToClassFactory();
$runner = new \Helmich\Schema2Class\Generator\GenerationRunner($loader, $inferrer, $factory);

$app->add(new \Helmich\Schema2Class\Command\GenerateCommand($runner, $loader));
$app->add(new \Helmich\Schema2Class\Command\GenerateSpecCommand($runner));

$app->run();
