options:
  targetPHPVersion: "7.4"
  singleLineSchema: true
  noSchemaMetadata: true
files:
  - input: "examples/basic/basic-example.json"
    options:
      targetDirectory: "examples/basic/generated"
      targetNamespace: "Example\\Basic"
