targetPHPVersion: "7.4"
options:
  singleLineSchema: true
  noDescriptionsInSchema: true
files:
  - input: "examples/basic/basic-example.json"
    targetDirectory: "examples/basic/generated"
    targetNamespace: "Example\\Basic"
